[package]
name = "display-gtk"
version = "0.1.1"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
futures = "0.3"
gtk = "0.15"
lipl-gatt-bluer = { git = "ssh://paul@www.paulmin.nl/home/paul/repo/rust/lipl-gatt-bluer.git" }
tokio = { version = "1", features = ["rt"] }
tracing = "0.1"
tracing-subscriber = "0.3"
