[workspace]
members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Paul Min"]
edition = "2021"
homepage = "https://paulusminus.github.io/lipl-book/"
license = "MIT"
repository = "https://github.com/paulusminus/lipl-display/"

[profile.release]
lto = true
strip = true
opt-level = "z"
