[package]
name = "lipl-display-gtk"
version = "0.1.1"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2021"

[profile.release]
lto = true
strip = true
opt-level = "z"

[dependencies]
anyhow = "1.0"
gtk = "0.16"
glib = { version = "0.16", features = ["log"] }
lipl-gatt-bluer = { git = "git://paulmin.nl/rust/lipl-gatt-bluer.git" }
log = "0.4"
