[package]
name = "lipl-gatt-zbus"
version = "0.4.0"
edition = "2018"

[patch.crates-io]
lipl-display-common = { git = "git://paulmin.nl/rust/lipl-display-common.git" }

[dependencies]
async-channel = "1.6"
async-io = "1.7"
derive_builder = "0.11.2"
lipl-display-common = "0.2.0"
thiserror = "1"
tracing = "0.1"
uuid = "1"
zbus = "2"
