[package]
name = "zbus-bluez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
event-listener = "2.5"
log = "0.4"
uuid = "1"
zbus = { version = "2", default-features = false, features = ["tokio"] }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros", "signal"]}
env_logger = "0.9"
uuid = "1"
