[package]
name = "lipl-gatt-bluer"
version = "0.1.14"
edition = "2021"

[profile.release]
lto = true

[dependencies]
bluer = { version = "0.13" }
futures = "0.3"
tokio = { version = "1", features = ["rt", "sync"] }
thiserror = "1"
tracing = "0.1"
