[package]
name = "zbus-bluez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus = "2"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"]}
# futures = "0.3"
