[package]
name = "lipl-display-gtk"
version = "0.1.1"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0"
gtk = "0.15"
lipl-gatt-bluer = { git = "git://paulmin.nl/lipl-gatt-bluer.git", branch = "stream" }
tracing = "0.1"
tracing-subscriber = "0.3"
