[package]
name = "lipl-display-egui"
version = "0.1.1"
edition = "2021"

[profile.release]
lto = true
opt-level = "z"
strip = true

[dependencies]
eframe = { version = "0.18", default-features = false }
lipl-gatt-bluer = { git = "git://paulmin.nl/rust/lipl-gatt-bluer.git" }
log = "0.4"
simple_logger = "2"
