[package]
name = "lipl-display-gtk"
version = "0.1.1"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2021"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0"
gtk = "0.15"
glib = { version = "0.15", features = ["log"] }
lipl-gatt-bluer = { git = "git://paulmin.nl/lipl-gatt-bluer.git", branch = "stream" }
log = "0.4"
