cargo-features = ["strip"]

[package]
name = "lipl-display-egui"
version = "0.1.1"
edition = "2021"

[profile.release]
lto = true
opt-level = "z"
strip = true

[dependencies]
eframe = { version = "0.16", default-features = false, features = ["egui_glow"] }
futures = "0.3"
lipl-gatt-bluer = { git = "git://paulmin.nl/lipl-gatt-bluer.git" }
tokio = { version = "1", features = ["rt", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
