[package]
name = "lipl-gatt-bluer"
version = "0.1.14"
edition = "2021"

[profile.release]
lto = true

[dependencies]
bluer = { version = "0.15", features = ["bluetoothd"] }
futures = "0.3"
lipl-display-common = { git = "git://paulmin.nl/rust/lipl-display-common.git" }
log = "0.4"
pin-project = "1"
thiserror = "1"
tokio = { version = "1", features = ["rt", "sync"] }
uuid = "1"

[dev-dependencies]
simple_logger = "2"
log = "0.4"
