[package]
name = "display-egui"
version = "0.1.1"
edition = "2021"

[dependencies]
eframe = { version = "0.16", default-features = false, features = ["egui_glow"] }
futures = "0.3"
lipl-gatt-bluer = { git = "ssh://paul@www.paulmin.nl/home/paul/repo/rust/lipl-gatt-bluer.git" }
tokio = { version = "1", features = ["rt", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
