[package]
name = "lipl-gatt-bluer"
version = "0.1.12"
edition = "2021"

[dependencies]
bluer = { version = "0.13" }
futures = "0.3"
tokio = { version = "1", features = ["rt", "sync"] }
tracing = "0.1"
