[package]
name = "lipl-gatt-zbus"
version = "0.1.2"
edition = "2018"

[dependencies]
async-channel = "1.6"
async-io = "1.7"
derive_builder = "0.11.2"
lipl-display-common = { git = "git://paulmin.nl/rust/lipl-display-common.git", branch = "main" }
thiserror = "1"
tracing = "0.1"
uuid = "1"
zbus = "2"
