[package]
name = "lipl-gatt-zbus"
version = "0.3.0"
edition = "2018"

[dependencies]
async-channel = "1.6"
async-io = "1.7"
derive_builder = "0.11.2"
lipl-display-common = { version = "0.2.0", registry = "paulmin-nl" }
thiserror = "1"
tracing = "0.1"
uuid = "1"
zbus = "2"
