[package]
authors = ["Paul Min"]
description = "Displaying part on the screen using gtk"
edition = "2021"
homepage = "https://paulusminus.github.io/lipl-book/"
license = "MIT"
name = "lipl-display-gtk"
repository = "https://github.com/paulusminus/lipl-display/"
version = "0.1.3"

[dependencies]
anyhow = "1.0"
gtk = "0.18"
glib = { version = "0.18", features = ["log"] }
lipl-gatt-bluer = "0.1"
log = "0.4"
