[package]
license = "MIT"
name = "lipl-display-gtk"
version = "0.1.2"
authors = ["Paul Min <info@paulmin.nl>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
gtk = "0.18"
glib = { version = "0.18", features = ["log"] }
lipl-gatt-bluer = { path = "../lipl-gatt-bluer" }
log = "0.4"
