[package]
authors.workspace = true
description = "Displaying part on the screen using gtk"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-display-gtk"
repository.workspace = true
version = "0.1.5"

[dependencies]
anyhow = "1.0"
gtk = "0.18"
glib = { version = "0.18", features = ["log"] }
lipl-gatt-bluer = "0.1"
log = "0.4"
