[package]
name = "login-poweroff-reboot-zbus"
description = "Poweroff or reboot machine using dbus interface logind"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
zbus = { workspace = true, features = ["tokio"] }
