[package]
name = "login-poweroff-reboot-zbus"
description = "reboot or poweroff machine by sending dbus message to login manager"
version = "0.3.1"
edition = "2021"
license = "MIT"

[dependencies]
zbus = "3"
