[package]
name = "lipl-display-freya"
version = "0.1.0"
edition = "2024"

[features]
default = []
gatt = ["dep:lipl-gatt-bluer"]

[dependencies]
freya = { workspace = true }
futures-util = { workspace = true }
lipl-display-common = { workspace = true }
lipl-gatt-bluer = { workspace = true, optional = true }
tokio = { workspace = true, features = ["time", "rt", "rt-multi-thread"] }
deserialize-lines = { workspace = true }
