#!/bin/sh
set -e

LIPL_HOME=/usr/bin
LIPL_USER=lipl
LIPL_NAME="Lipl Display User"
ADDGROUP="video"

case "$1" in
install|upgrade)
  # 1. create user if not existing
  if ! getent passwd | grep -q "^$LIPL_USER:"; then
    echo -n "Adding system user $LIPL_USER.."
    adduser --quiet \
            --system \
            --no-create-home \
            --disabled-password \
            $LIPL_USER 2>/dev/null || true
    echo "..done"
  fi

  # 2. adjust passwd entry
  usermod -c "$LIPL_NAME" \
          -d $LIPL_HOME \
          -s /usr/bin/lipl-display-slint \
             $LIPL_USER

  # 3. Add the user to the ADDGROUP group
  if test -n $ADDGROUP
  then
      if ! groups $LIPL_USER | cut -d: -f2 | \
         grep -qw $LIPLGROUP; then
           adduser $LIPL_USER $ADDGROUP
      fi
  fi

  ;;
esac  

#DEBHELPER#
