[package]
name = "lipl-display-femtovg"
authors.workspace = true
description = "Displaying part on the screen using femtovg"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version = "0.4.1"

[dependencies]
femtovg = { version = "0.7", default-features = false }
glutin = { version = "0.30", default-features = false }
glutin-winit = { version = "0.3", default-features = false, features = ["egl", "wayland"] }
lipl-display-common = { version = "0.4.0", path = "../lipl-display-common" }
lipl-gatt-bluer = { version = "0.4.0", path = "../lipl-gatt-bluer" }
log = "0.4"
env_logger = "0.10"
raw-window-handle = "0.6"
winit = { version = "0.28", default-features = false, features = ["wayland"] }

