[package]
name = "lipl-display-femtovg"
authors.workspace = true
description = "Displaying part on the screen using femtovg"
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
femtovg = { version = "0.8", default-features = false }
glutin = { version = "0.31", default-features = false }
glutin-winit = { version = "0.4", default-features = false, features = ["egl", "wayland"] }
lipl-display-common = { version = "0.4", path = "../lipl-display-common" }
lipl-gatt-bluer = { version = "0.4", path = "../lipl-gatt-bluer" }
log = "0.4"
env_logger = "0.11"
raw-window-handle = "0.5"
winit = { version = "0.29", default-features = false, features = ["rwh_05", "wayland"] }

