[package]
name = "lipl-display-blitz"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
dioxus-native = "0.7.0-rc.3"
dioxus = "0.7.0-rc.3"
tokio = { version = "1.42", features = ["rt", "time"] }
tracing-subscriber = "0.3"
chrono = "0.4.41"
json-lines = { path = "../json-lines" }
