[package]
name = "lipl-display-blitz"
version = "0.1.0"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
blitz-dom = { git = "https://github.com/dioxuslabs/blitz" }
mini-dxn = { git = "https://github.com/dioxuslabs/blitz", default-features = false, features = [
    "tracing",
    "autofocus",
    "cpu_backend",
    "net",
] }
dioxus = { version = "=0.7.0-alpha.1" }
tokio = { version = "1.42", features = ["rt", "time"] }
tracing-subscriber = "0.3"
chrono = "0.4.41"
