import { VerticalBox } from "std-widgets.slint";
import "./Roboto-Regular.ttf";

export component LiplDisplay inherits Window {
    title: "Lipl Display";
    default-font-family: "Roboto";
    background: dark ? black : white;
    preferred-width: 640px;
    preferred-height: 480px;

    in property<bool> dark: false;
    in property<string> part: "";
    in property<string> status: "";
    in-out property<int> fontsize: 40;

    VerticalBox {
        padding-left: 0.03 * root.width;
        padding-right: 0.03 * root.width;
        padding-top: 0.03 * root.height;
        padding-bottom: 0.03 * root.height;
        
        part:= Text {
            color: root.dark ? white : black;
            font-size: root.fontsize * 1px;
            text: "\{root.part}";
        }
        status:= Text {
            color: root.dark ? white : black;
            font-size: root.fontsize * 0.8 * 1px;
            text: "\{root.status}";
            height: 5%;
        }
    }
}
