name: Rust

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ubuntu dependencies
        run: sudo apt update && sudo apt install libdbus-1-dev libgtk-4-dev libudev-dev libgbm-dev libxkbcommon-dev libfontconfig1-dev libseat-dev libsystemd-dev libinput-dev libsdl2-dev libsdl2-ttf-dev
      - name: Formatting
        run: cargo fmt --all --check
      - name: Clippy Slint version
        run: cargo clippy --no-deps -p lipl-display-slint -- -D warnings
      - name: Clippy Femtovg version
        run: cargo clippy --no-deps -p lipl-display-femtovg -- -D warnings
      - name: Build Slint version
        run: cargo build --release -p lipl-display-slint
      - name: Build Femtovg version
        run: cargo build --release -p lipl-display-femtovg
