name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install ubuntu dependencies
      run: sudo apt update && sudo apt install libdbus-1-dev libgtk-4-dev libudev-dev libgbm-dev libxkbcommon-dev libfontconfig1-dev libseat-dev libsystemd-dev libinput-dev libsdl2-dev libsdl2-ttf-dev
    - uses: paulusminus/rust-check@v5
      with:
        build: true
