[package]
license = "MIT"
name = "lipl-display-egui"
version = "0.1.1"
edition = "2021"

[dependencies]
eframe = { version = "0.22", default-features = false, features = ["default_fonts", "glow"] }
lipl-gatt-bluer = { path = "../lipl-gatt-bluer" }
log = "0.4"
simple_logger = "4"
