[package]
authors.workspace = true
description = "Displaying part on the screen using egui"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-display-egui"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = "1"
eframe = { version = "0.22", default-features = false, features = ["default_fonts", "glow"] }
lipl-display-common = { version = "0.3.0", path = "../lipl-display-common" }
lipl-gatt-bluer = { version = "0.3.0", path = "../lipl-gatt-bluer" }
log = "0.4"
simple_logger = "4"
