[package]
authors = ["Paul Min"]
description = "Displaying part on the screen using egui"
edition = "2021"
homepage = "https://paulusminus.github.io/lipl-book/"
license = "MIT"
name = "lipl-display-egui"
repository = "https://github.com/paulusminus/lipl-display/"
version = "0.1.2"

[dependencies]
eframe = { version = "0.22", default-features = false, features = ["default_fonts", "glow"] }
lipl-gatt-bluer = "0.1"
log = "0.4"
simple_logger = "4"
