[package]
authors.workspace = true
description = "Displaying part on the screen using egui"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "lipl-display-egui"
repository.workspace = true
version = "0.1.3"

[dependencies]
eframe = { version = "0.22", default-features = false, features = ["default_fonts", "glow"] }
lipl-gatt-bluer = "0.1"
log = "0.4"
simple_logger = "4"
